name: Deploy

on:
  release:
    types: [published]

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    timeout-minutes: 30
    steps:
      - name: Environment ${{ vars.NAME }} branch ${{ github.ref_name }}
        env: 
          NAME: ${{ vars.NAME }}
        run: echo $NAME
