name: Deploy

on:
  push:
    branches:
      - '**' # All branches
    paths:
      - '**'
  release:
    types: [published]

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    timeout-minutes: 30
    steps:
      - name: Environment ${{ vars.NAME }}
        run: vars

      # - name: Check out code
      #   uses: actions/checkout@v4
      #   with:
      #     fetch-depth: 2

      # - name: Build Storefront
      #   uses: ./.github/actions/build
      #   with:
      #     app: storefront

      # - name: Deploy Storefront
      #   run: pnpm turbo run deploy --filter=storefront... -- --token ${{ secrets.token }} --force
        
      # - name: Display Deployment Log
      #   run: jq . ./apps/storefront/h2_deploy_log.json
